export type PdfFleetVehicle = { registration: string; displayName: string };

export const PDF_FLEET: PdfFleetVehicle[] = [
  { registration: "KN73XLB", displayName: "Mercedes-Benz EQE" },
  { registration: "KN73XLA", displayName: "Mercedes-Benz EQE" },
  { registration: "KU73MVW", displayName: "Mercedes-Benz EQE" },
  { registration: "WH74EJF", displayName: "Mercedes-Benz EQE" },
  { registration: "WG74KFJ", displayName: "Mercedes-Benz EQE" },
  { registration: "KR74WDL", displayName: "Mercedes-Benz EQE" },
  { registration: "EN73UBZ", displayName: "Mercedes-Benz EQE" },
  { registration: "WN20NKU", displayName: "Mercedes-Benz E300" },
  { registration: "BD20XPU", displayName: "Mercedes-Benz E300" },
  { registration: "GY69NWL", displayName: "Mercedes-Benz E300" },
  { registration: "KT68VYM", displayName: "Mercedes-Benz E220D" },
  { registration: "FX19FXC", displayName: "Mercedes-Benz E220D" },
  { registration: "CA19UTF", displayName: "Mercedes-Benz E220D" },
  { registration: "OWN19XNX", displayName: "Mercedes-Benz E220D" },
  { registration: "BX19ZMY", displayName: "Mercedes-Benz E220D" },
  { registration: "BU19ACJ", displayName: "Mercedes-Benz E220D" },
  { registration: "WD19SNN", displayName: "Mercedes-Benz E220D" },
  { registration: "KP69WOR", displayName: "Mercedes-Benz E220D" },
  { registration: "LR69UCG", displayName: "Mercedes-Benz E220D" },
  { registration: "HX19VXB", displayName: "Mercedes-Benz E220D" },
  { registration: "OU68SXP", displayName: "Mercedes-Benz E220D" },
  { registration: "BN68MYZ", displayName: "Mercedes-Benz E220D" },
  { registration: "BN68NHP", displayName: "Mercedes-Benz E220D" },
  { registration: "AK69CKJ", displayName: "Mercedes-Benz E220D" },
  { registration: "BL19JDZ", displayName: "Mercedes-Benz E220D" },
  { registration: "PO18UTT", displayName: "Mercedes-Benz E220D" },
  { registration: "BN17CVA", displayName: "Mercedes-Benz Vito" },
  { registration: "KO18HKE", displayName: "Mercedes-Benz Vito" },
  { registration: "KT18ATF", displayName: "Mercedes-Benz Vito" },
  { registration: "KW18TMV", displayName: "Mercedes-Benz Vito" },
  { registration: "WR16UED", displayName: "Mercedes-Benz Vito" },
  { registration: "WR19UFG", displayName: "Mercedes-Benz Vito" },
  { registration: "KF19UCJ", displayName: "Toyota Corolla" },
  { registration: "KF19UCM", displayName: "Toyota Corolla" },
  { registration: "KF19UCN", displayName: "Toyota Corolla" },
  { registration: "LT69GSY", displayName: "Toyota Corolla" },
  { registration: "LT69GSZ", displayName: "Toyota Corolla" },
  { registration: "LT69GTU", displayName: "Toyota Corolla" },
  { registration: "LL68CRZ", displayName: "Toyota Auris Estate" },
  { registration: "LM68KRD", displayName: "Toyota Auris Estate" },
  { registration: "LM68KRG", displayName: "Toyota Auris Estate" },
  { registration: "LM68KRJ", displayName: "Toyota Auris Estate" },
  { registration: "LM68KRO", displayName: "Toyota Auris Estate" },
  { registration: "LM68KRU", displayName: "Toyota Auris Estate" },
  { registration: "LR16VTY", displayName: "Toyota Prius" },
  { registration: "AF70MWK", displayName: "Tesla Model 3" },
  { registration: "BJ20LGX", displayName: "Tesla Model 3" },
  { registration: "MJ69YPN", displayName: "Tesla Model 3" },
  { registration: "BK70WYM", displayName: "Tesla Model 3" },
  { registration: "BT69TEJ", displayName: "Tesla Model 3" },
  { registration: "LA69AXF", displayName: "Tesla Model 3" },
  { registration: "LA69AYB", displayName: "Tesla Model 3" },
  { registration: "LB69OFY", displayName: "Tesla Model 3" },
  { registration: "LD20COJ", displayName: "Tesla Model 3" },
  { registration: "LD20FCE", displayName: "Tesla Model 3" },
  { registration: "WN20EJA", displayName: "Tesla Model 3" },
  { registration: "BN20XMX", displayName: "Jaguar I-Pace" },
  { registration: "GX70UBD", displayName: "Jaguar I-Pace" },
  { registration: "EF70ZPZ", displayName: "Hyundai Ioniq" },
  { registration: "EF70ZPY", displayName: "Hyundai Ioniq" },
  { registration: "EF70ZVM", displayName: "Hyundai Ioniq" },
  { registration: "EF70ZYA", displayName: "Hyundai Ioniq" },
  { registration: "EF70ZYD", displayName: "Hyundai Ioniq" },
  { registration: "GU72DVP", displayName: "Hyundai Ioniq" },
  { registration: "FL70EUV", displayName: "Hyundai Ioniq" },
  { registration: "EK70BKJ", displayName: "Hyundai Ioniq" },
  { registration: "YC72HZM", displayName: "MG 5 EV" },
  { registration: "YF22UVZ", displayName: "MG 5 EV" },
  { registration: "YF22UWK", displayName: "MG 5 EV" },
  { registration: "YF22UWM", displayName: "MG 5 EV" },
  { registration: "YF22UWT", displayName: "MG 5 EV" },
  { registration: "YF22UXC", displayName: "MG 5 EV" },
  { registration: "YF22UXY", displayName: "MG 5 EV" },
  { registration: "YG71LCZ", displayName: "MG 5 EV" },
  { registration: "MD25AYY", displayName: "Ford Tourneo Custom" },
  { registration: "MD25DDZ", displayName: "Ford Tourneo Custom" },
  { registration: "RX25CME", displayName: "Ford Tourneo Custom" },
];

export const PDF_FLEET_FAMILIES = [...new Set(PDF_FLEET.map((vehicle) => vehicle.displayName))];
