export type VchLetterVehicle = { reg: string; model: string };

/** Source fleet copied from Areeb-Ansari43/VCHLetter main at inspection time. */
export const VCHLETTER_FLEET: VchLetterVehicle[] = [
  {reg:"AF70 MYK",model:"TESLA MODEL 3"},{reg:"BD20 XPU",model:"MERCEDES-BENZ E300"},{reg:"BJ20 L6X",model:"TESLA MODEL 3"},{reg:"BK70 WYM",model:"TESLA MODEL 3"},{reg:"BL19 JDZ",model:"MERCEDES-BENZ E220D"},{reg:"BN17 CVA",model:"MERCEDES-BENZ VITO"},{reg:"BN20 MXL",model:"JAGUAR I-PACE"},{reg:"BN60 MYZ",model:"MERCEDES-BENZ E220D"},{reg:"BN60 NHP",model:"MERCEDES-BENZ E220D"},{reg:"BT69 TEJ",model:"TESLA MODEL 3"},
  {reg:"RE21 NRX",model:"MG 5 EV"},{reg:"BU19 ACJ",model:"MERCEDES-BENZ E220D"},{reg:"BV18 WNA",model:"MERCEDES-BENZ E220D"},{reg:"BX19 ZMY",model:"MERCEDES-BENZ E220D"},{reg:"CA19 UTF",model:"MERCEDES-BENZ E220D"},{reg:"EF70 ZPZ",model:"HYUNDAI IONIQ"},{reg:"EF70 ZVM",model:"HYUNDAI IONIQ"},{reg:"EF70 ZYD",model:"HYUNDAI IONIQ"},{reg:"EK70 AG0",model:"HYUNDAI IONIQ"},{reg:"EN73 UBZ",model:"MERCEDES-BENZ EQE 300"},
  {reg:"FL70 EUV",model:"HYUNDAI IONIQ"},{reg:"FX19 FXC",model:"MERCEDES-BENZ E220D"},{reg:"GU72 DVP",model:"HYUNDAI IONIQ"},{reg:"GX70 UBD",model:"JAGUAR I-PACE"},{reg:"GY69 NVL",model:"MERCEDES-BENZ E300"},{reg:"HX19 VXB",model:"MERCEDES-BENZ E220D"},{reg:"HX19 VZG",model:"MERCEDES-BENZ E220D"},{reg:"KF19 UCJ",model:"TOYOTA COROLLA"},{reg:"KF19 UCN",model:"TOYOTA COROLLA"},{reg:"KN73 XLA",model:"MERCEDES-BENZ EQE 300"},
  {reg:"KN73 XLB",model:"MERCEDES-BENZ EQE 300"},{reg:"KO18 HKE",model:"MERCEDES-BENZ VITO"},{reg:"KP69 WOR",model:"MERCEDES-BENZ E220D"},{reg:"KR74 WDL",model:"MERCEDES-BENZ EQE 350+"},{reg:"AK69 CKJ",model:"MERCEDES-BENZ E220D"},{reg:"KT18 ATF",model:"MERCEDES-BENZ VITO"},{reg:"KT68 VYM",model:"MERCEDES-BENZ E220D"},{reg:"KU73 MVW",model:"MERCEDES-BENZ E300"},{reg:"KL18 TMV",model:"MERCEDES-BENZ VITO"},{reg:"LA69 AXF",model:"TESLA MODEL 3"},
  {reg:"LA69 AYB",model:"TESLA MODEL 3"},{reg:"LB69 OFY",model:"TESLA MODEL 3"},{reg:"LD20 COJ",model:"TESLA MODEL 3"},{reg:"LD20 FCE",model:"TESLA MODEL 3"},{reg:"LL68 CRZ",model:"TOYOTA AURIS"},{reg:"LL68 CRV",model:"TOYOTA AURIS"},{reg:"LL68 KRJ",model:"TOYOTA AURIS"},{reg:"LM68 KRG",model:"TOYOTA AURIS"},{reg:"LM68 KRJ",model:"TOYOTA AURIS"},{reg:"LM68 KRO",model:"TOYOTA AURIS"},
  {reg:"LM68 KRU",model:"TOYOTA AURIS"},{reg:"LR16 VTY",model:"TOYOTA PRIUS"},{reg:"LR69 UCG",model:"MERCEDES-BENZ E220D"},{reg:"LT69 GSU",model:"TOYOTA COROLLA"},{reg:"LT69 G5V",model:"TOYOTA COROLLA"},{reg:"LT69 GSV",model:"TOYOTA COROLLA"},{reg:"LT69 GSZ",model:"TOYOTA COROLLA"},{reg:"LT69 GTU",model:"TOYOTA COROLLA"},{reg:"MD25 AYY",model:"FORD TOURNEO CUSTOM"},{reg:"MD25 DCX",model:"FORD TOURNEO CUSTOM"},
  {reg:"MJ69 YPN",model:"TESLA MODEL 3"},{reg:"MV68 OGF",model:"MERCEDES-BENZ E220D"},{reg:"MV68 OHB",model:"MERCEDES-BENZ E220D"},{reg:"DU68 SXP",model:"MERCEDES-BENZ E220D"},{reg:"OW19 XXN",model:"MERCEDES-BENZ E220D"},{reg:"PO18 UTT",model:"MERCEDES-BENZ E220D"},{reg:"RE21 NRV",model:"MG 5 EV"},{reg:"RE21 NRZ",model:"MG 5 EV"},{reg:"RE21 NSF",model:"MG 5 EV"},{reg:"RE21 NSU",model:"MG 5 EV"},
  {reg:"RX25 CME",model:"FORD TOURNEO CUSTOM"},{reg:"SF19 WPW",model:"MERCEDES-BENZ VITO"},{reg:"TD19 5NN",model:"MERCEDES-BENZ E220D"},{reg:"WG74 KFJ",model:"MERCEDES-BENZ EQE 300"},{reg:"IH74 E3F",model:"MERCEDES-BENZ EQE 300"},{reg:"IHN2 0E3",model:"TESLA MODEL 3"},{reg:"IN20 NKU",model:"MERCEDES-BENZ E300"},{reg:"WR16 UED",model:"MERCEDES-BENZ VITO"},{reg:"WR19 UFG",model:"MERCEDES-BENZ VITO"},{reg:"YC72 HZM",model:"MG 5 EV"},
  {reg:"YF22 UVZ",model:"MG 5 EV"},{reg:"YF22 UWK",model:"MG 5 EV"},{reg:"YF22 UWR",model:"MG 5 EV"},{reg:"YF22 UWT",model:"MG 5 EV"},{reg:"YF22 UWA",model:"MG 5 EV"},{reg:"YF22 UXA",model:"MG 5 EV"},{reg:"YF22 UXC",model:"MG 5 EV"},{reg:"YF22 UXY",model:"MG 5 EV"},{reg:"YH71 JHL",model:"MG 5 EV"},
];

export const normalizeVchReg = (value: string) => value.replace(/\s+/g, "").toUpperCase();
