/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesIdRouteImport } from './routes/vehicles.$id'
import { Route as ApiPublicExpiryAlertsRouteImport } from './routes/api/public/expiry-alerts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIdRoute = VehiclesIdRouteImport.update({
  id: '/vehicles/$id',
  path: '/vehicles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExpiryAlertsRoute = ApiPublicExpiryAlertsRouteImport.update({
  id: '/api/public/expiry-alerts',
  path: '/api/public/expiry-alerts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/vehicles/$id': typeof VehiclesIdRoute
  '/api/public/expiry-alerts': typeof ApiPublicExpiryAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/vehicles/$id': typeof VehiclesIdRoute
  '/api/public/expiry-alerts': typeof ApiPublicExpiryAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/vehicles/$id': typeof VehiclesIdRoute
  '/api/public/expiry-alerts': typeof ApiPublicExpiryAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/vehicles/$id' | '/api/public/expiry-alerts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/vehicles/$id' | '/api/public/expiry-alerts'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/vehicles/$id'
    | '/api/public/expiry-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  VehiclesIdRoute: typeof VehiclesIdRoute
  ApiPublicExpiryAlertsRoute: typeof ApiPublicExpiryAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$id': {
      id: '/vehicles/$id'
      path: '/vehicles/$id'
      fullPath: '/vehicles/$id'
      preLoaderRoute: typeof VehiclesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/expiry-alerts': {
      id: '/api/public/expiry-alerts'
      path: '/api/public/expiry-alerts'
      fullPath: '/api/public/expiry-alerts'
      preLoaderRoute: typeof ApiPublicExpiryAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  VehiclesIdRoute: VehiclesIdRoute,
  ApiPublicExpiryAlertsRoute: ApiPublicExpiryAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
