/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappLeadsRouteImport } from './routes/whatsapp-leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriverMileageRouteImport } from './routes/driver-mileage'
import { Route as AddVehicleRouteImport } from './routes/add-vehicle'
import { Route as AccidentCasesRouteImport } from './routes/accident-cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles.index'
import { Route as ServiceHistoryIndexRouteImport } from './routes/service-history.index'
import { Route as VehiclesRegRouteImport } from './routes/vehicles.$reg'
import { Route as ServiceHistoryNewRouteImport } from './routes/service-history.new'
import { Route as ApiPublicTelegramBotRouteImport } from './routes/api/public/telegram-bot'
import { Route as ApiPublicExpiryAlertsRouteImport } from './routes/api/public/expiry-alerts'
import { Route as ApiPublicAiIntakeRouteImport } from './routes/api/public/ai-intake'
import { Route as ApiPublicAgentWebhookRouteImport } from './routes/api/public/agent-webhook'

const WhatsappLeadsRoute = WhatsappLeadsRouteImport.update({
  id: '/whatsapp-leads',
  path: '/whatsapp-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverMileageRoute = DriverMileageRouteImport.update({
  id: '/driver-mileage',
  path: '/driver-mileage',
  getParentRoute: () => rootRouteImport,
} as any)
const AddVehicleRoute = AddVehicleRouteImport.update({
  id: '/add-vehicle',
  path: '/add-vehicle',
  getParentRoute: () => rootRouteImport,
} as any)
const AccidentCasesRoute = AccidentCasesRouteImport.update({
  id: '/accident-cases',
  path: '/accident-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceHistoryIndexRoute = ServiceHistoryIndexRouteImport.update({
  id: '/service-history/',
  path: '/service-history/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRegRoute = VehiclesRegRouteImport.update({
  id: '/vehicles/$reg',
  path: '/vehicles/$reg',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceHistoryNewRoute = ServiceHistoryNewRouteImport.update({
  id: '/service-history/new',
  path: '/service-history/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramBotRoute = ApiPublicTelegramBotRouteImport.update({
  id: '/api/public/telegram-bot',
  path: '/api/public/telegram-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExpiryAlertsRoute = ApiPublicExpiryAlertsRouteImport.update({
  id: '/api/public/expiry-alerts',
  path: '/api/public/expiry-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiIntakeRoute = ApiPublicAiIntakeRouteImport.update({
  id: '/api/public/ai-intake',
  path: '/api/public/ai-intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentWebhookRoute = ApiPublicAgentWebhookRouteImport.update({
  id: '/api/public/agent-webhook',
  path: '/api/public/agent-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accident-cases': typeof AccidentCasesRoute
  '/add-vehicle': typeof AddVehicleRoute
  '/driver-mileage': typeof DriverMileageRoute
  '/login': typeof LoginRoute
  '/whatsapp-leads': typeof WhatsappLeadsRoute
  '/service-history/new': typeof ServiceHistoryNewRoute
  '/vehicles/$reg': typeof VehiclesRegRoute
  '/service-history/': typeof ServiceHistoryIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/api/public/agent-webhook': typeof ApiPublicAgentWebhookRoute
  '/api/public/ai-intake': typeof ApiPublicAiIntakeRoute
  '/api/public/expiry-alerts': typeof ApiPublicExpiryAlertsRoute
  '/api/public/telegram-bot': typeof ApiPublicTelegramBotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accident-cases': typeof AccidentCasesRoute
  '/add-vehicle': typeof AddVehicleRoute
  '/driver-mileage': typeof DriverMileageRoute
  '/login': typeof LoginRoute
  '/whatsapp-leads': typeof WhatsappLeadsRoute
  '/service-history/new': typeof ServiceHistoryNewRoute
  '/vehicles/$reg': typeof VehiclesRegRoute
  '/service-history': typeof ServiceHistoryIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
  '/api/public/agent-webhook': typeof ApiPublicAgentWebhookRoute
  '/api/public/ai-intake': typeof ApiPublicAiIntakeRoute
  '/api/public/expiry-alerts': typeof ApiPublicExpiryAlertsRoute
  '/api/public/telegram-bot': typeof ApiPublicTelegramBotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accident-cases': typeof AccidentCasesRoute
  '/add-vehicle': typeof AddVehicleRoute
  '/driver-mileage': typeof DriverMileageRoute
  '/login': typeof LoginRoute
  '/whatsapp-leads': typeof WhatsappLeadsRoute
  '/service-history/new': typeof ServiceHistoryNewRoute
  '/vehicles/$reg': typeof VehiclesRegRoute
  '/service-history/': typeof ServiceHistoryIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/api/public/agent-webhook': typeof ApiPublicAgentWebhookRoute
  '/api/public/ai-intake': typeof ApiPublicAiIntakeRoute
  '/api/public/expiry-alerts': typeof ApiPublicExpiryAlertsRoute
  '/api/public/telegram-bot': typeof ApiPublicTelegramBotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accident-cases'
    | '/add-vehicle'
    | '/driver-mileage'
    | '/login'
    | '/whatsapp-leads'
    | '/service-history/new'
    | '/vehicles/$reg'
    | '/service-history/'
    | '/vehicles/'
    | '/api/public/agent-webhook'
    | '/api/public/ai-intake'
    | '/api/public/expiry-alerts'
    | '/api/public/telegram-bot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accident-cases'
    | '/add-vehicle'
    | '/driver-mileage'
    | '/login'
    | '/whatsapp-leads'
    | '/service-history/new'
    | '/vehicles/$reg'
    | '/service-history'
    | '/vehicles'
    | '/api/public/agent-webhook'
    | '/api/public/ai-intake'
    | '/api/public/expiry-alerts'
    | '/api/public/telegram-bot'
  id:
    | '__root__'
    | '/'
    | '/accident-cases'
    | '/add-vehicle'
    | '/driver-mileage'
    | '/login'
    | '/whatsapp-leads'
    | '/service-history/new'
    | '/vehicles/$reg'
    | '/service-history/'
    | '/vehicles/'
    | '/api/public/agent-webhook'
    | '/api/public/ai-intake'
    | '/api/public/expiry-alerts'
    | '/api/public/telegram-bot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccidentCasesRoute: typeof AccidentCasesRoute
  AddVehicleRoute: typeof AddVehicleRoute
  DriverMileageRoute: typeof DriverMileageRoute
  LoginRoute: typeof LoginRoute
  WhatsappLeadsRoute: typeof WhatsappLeadsRoute
  ServiceHistoryNewRoute: typeof ServiceHistoryNewRoute
  VehiclesRegRoute: typeof VehiclesRegRoute
  ServiceHistoryIndexRoute: typeof ServiceHistoryIndexRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
  ApiPublicAgentWebhookRoute: typeof ApiPublicAgentWebhookRoute
  ApiPublicAiIntakeRoute: typeof ApiPublicAiIntakeRoute
  ApiPublicExpiryAlertsRoute: typeof ApiPublicExpiryAlertsRoute
  ApiPublicTelegramBotRoute: typeof ApiPublicTelegramBotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp-leads': {
      id: '/whatsapp-leads'
      path: '/whatsapp-leads'
      fullPath: '/whatsapp-leads'
      preLoaderRoute: typeof WhatsappLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-mileage': {
      id: '/driver-mileage'
      path: '/driver-mileage'
      fullPath: '/driver-mileage'
      preLoaderRoute: typeof DriverMileageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-vehicle': {
      id: '/add-vehicle'
      path: '/add-vehicle'
      fullPath: '/add-vehicle'
      preLoaderRoute: typeof AddVehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accident-cases': {
      id: '/accident-cases'
      path: '/accident-cases'
      fullPath: '/accident-cases'
      preLoaderRoute: typeof AccidentCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-history/': {
      id: '/service-history/'
      path: '/service-history'
      fullPath: '/service-history/'
      preLoaderRoute: typeof ServiceHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$reg': {
      id: '/vehicles/$reg'
      path: '/vehicles/$reg'
      fullPath: '/vehicles/$reg'
      preLoaderRoute: typeof VehiclesRegRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-history/new': {
      id: '/service-history/new'
      path: '/service-history/new'
      fullPath: '/service-history/new'
      preLoaderRoute: typeof ServiceHistoryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram-bot': {
      id: '/api/public/telegram-bot'
      path: '/api/public/telegram-bot'
      fullPath: '/api/public/telegram-bot'
      preLoaderRoute: typeof ApiPublicTelegramBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/expiry-alerts': {
      id: '/api/public/expiry-alerts'
      path: '/api/public/expiry-alerts'
      fullPath: '/api/public/expiry-alerts'
      preLoaderRoute: typeof ApiPublicExpiryAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-intake': {
      id: '/api/public/ai-intake'
      path: '/api/public/ai-intake'
      fullPath: '/api/public/ai-intake'
      preLoaderRoute: typeof ApiPublicAiIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-webhook': {
      id: '/api/public/agent-webhook'
      path: '/api/public/agent-webhook'
      fullPath: '/api/public/agent-webhook'
      preLoaderRoute: typeof ApiPublicAgentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccidentCasesRoute: AccidentCasesRoute,
  AddVehicleRoute: AddVehicleRoute,
  DriverMileageRoute: DriverMileageRoute,
  LoginRoute: LoginRoute,
  WhatsappLeadsRoute: WhatsappLeadsRoute,
  ServiceHistoryNewRoute: ServiceHistoryNewRoute,
  VehiclesRegRoute: VehiclesRegRoute,
  ServiceHistoryIndexRoute: ServiceHistoryIndexRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
  ApiPublicAgentWebhookRoute: ApiPublicAgentWebhookRoute,
  ApiPublicAiIntakeRoute: ApiPublicAiIntakeRoute,
  ApiPublicExpiryAlertsRoute: ApiPublicExpiryAlertsRoute,
  ApiPublicTelegramBotRoute: ApiPublicTelegramBotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
